baseURL = "https://AlUgarov.github.io/gardengauge/"
languageCode = "en-us"
title = "GardenGauge Privacy Policy"
theme = "PaperMod"
# Ensure canonical links work when served from /app-privacy/
canonifyURLs = true
unsafe = true
